// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: kinetix.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerStatus int32

const (
	WorkerStatus_IDLE              WorkerStatus = 0
	WorkerStatus_BUSY              WorkerStatus = 1
	WorkerStatus_TERMINATING       WorkerStatus = 2
	WorkerStatus_CRITICAL_RESOURCE WorkerStatus = 3
)

// Enum value maps for WorkerStatus.
var (
	WorkerStatus_name = map[int32]string{
		0: "IDLE",
		1: "BUSY",
		2: "TERMINATING",
		3: "CRITICAL_RESOURCE",
	}
	WorkerStatus_value = map[string]int32{
		"IDLE":              0,
		"BUSY":              1,
		"TERMINATING":       2,
		"CRITICAL_RESOURCE": 3,
	}
)

func (x WorkerStatus) Enum() *WorkerStatus {
	p := new(WorkerStatus)
	*p = x
	return p
}

func (x WorkerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_kinetix_proto_enumTypes[0].Descriptor()
}

func (WorkerStatus) Type() protoreflect.EnumType {
	return &file_kinetix_proto_enumTypes[0]
}

func (x WorkerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerStatus.Descriptor instead.
func (WorkerStatus) EnumDescriptor() ([]byte, []int) {
	return file_kinetix_proto_rawDescGZIP(), []int{0}
}

type WorkerSignal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkerId        string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CpuPercentage   float32                `protobuf:"fixed32,2,opt,name=cpu_percentage,json=cpuPercentage,proto3" json:"cpu_percentage,omitempty"`
	TotalCores      uint32                 `protobuf:"varint,3,opt,name=total_cores,json=totalCores,proto3" json:"total_cores,omitempty"`
	TotalMemory     uint32                 `protobuf:"varint,4,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
	AvailableMemory uint32                 `protobuf:"varint,5,opt,name=available_memory,json=availableMemory,proto3" json:"available_memory,omitempty"`
	Status          WorkerStatus           `protobuf:"varint,6,opt,name=status,proto3,enum=kinetix.WorkerStatus" json:"status,omitempty"`
	IntegrityReport string                 `protobuf:"bytes,7,opt,name=integrity_report,json=integrityReport,proto3" json:"integrity_report,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkerSignal) Reset() {
	*x = WorkerSignal{}
	mi := &file_kinetix_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerSignal) ProtoMessage() {}

func (x *WorkerSignal) ProtoReflect() protoreflect.Message {
	mi := &file_kinetix_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerSignal.ProtoReflect.Descriptor instead.
func (*WorkerSignal) Descriptor() ([]byte, []int) {
	return file_kinetix_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerSignal) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerSignal) GetCpuPercentage() float32 {
	if x != nil {
		return x.CpuPercentage
	}
	return 0
}

func (x *WorkerSignal) GetTotalCores() uint32 {
	if x != nil {
		return x.TotalCores
	}
	return 0
}

func (x *WorkerSignal) GetTotalMemory() uint32 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

func (x *WorkerSignal) GetAvailableMemory() uint32 {
	if x != nil {
		return x.AvailableMemory
	}
	return 0
}

func (x *WorkerSignal) GetStatus() WorkerStatus {
	if x != nil {
		return x.Status
	}
	return WorkerStatus_IDLE
}

func (x *WorkerSignal) GetIntegrityReport() string {
	if x != nil {
		return x.IntegrityReport
	}
	return ""
}

type BrainSignal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*BrainSignal_Task
	//	*BrainSignal_Ack
	Event         isBrainSignal_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrainSignal) Reset() {
	*x = BrainSignal{}
	mi := &file_kinetix_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrainSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrainSignal) ProtoMessage() {}

func (x *BrainSignal) ProtoReflect() protoreflect.Message {
	mi := &file_kinetix_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrainSignal.ProtoReflect.Descriptor instead.
func (*BrainSignal) Descriptor() ([]byte, []int) {
	return file_kinetix_proto_rawDescGZIP(), []int{1}
}

func (x *BrainSignal) GetEvent() isBrainSignal_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *BrainSignal) GetTask() *TaskAssignment {
	if x != nil {
		if x, ok := x.Event.(*BrainSignal_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *BrainSignal) GetAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Event.(*BrainSignal_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isBrainSignal_Event interface {
	isBrainSignal_Event()
}

type BrainSignal_Task struct {
	Task *TaskAssignment `protobuf:"bytes,1,opt,name=task,proto3,oneof"`
}

type BrainSignal_Ack struct {
	Ack *HeartbeatAck `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*BrainSignal_Task) isBrainSignal_Event() {}

func (*BrainSignal_Ack) isBrainSignal_Event() {}

type TaskAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WasmBinary    []byte                 `protobuf:"bytes,2,opt,name=wasm_binary,json=wasmBinary,proto3" json:"wasm_binary,omitempty"`
	FuelLimit     uint32                 `protobuf:"varint,3,opt,name=fuel_limit,json=fuelLimit,proto3" json:"fuel_limit,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_kinetix_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_kinetix_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_kinetix_proto_rawDescGZIP(), []int{2}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetWasmBinary() []byte {
	if x != nil {
		return x.WasmBinary
	}
	return nil
}

func (x *TaskAssignment) GetFuelLimit() uint32 {
	if x != nil {
		return x.FuelLimit
	}
	return 0
}

func (x *TaskAssignment) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_kinetix_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_kinetix_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_kinetix_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatAck) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

var File_kinetix_proto protoreflect.FileDescriptor

const file_kinetix_proto_rawDesc = "" +
	"\n" +
	"\rkinetix.proto\x12\akinetix\"\x9b\x02\n" +
	"\fWorkerSignal\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12%\n" +
	"\x0ecpu_percentage\x18\x02 \x01(\x02R\rcpuPercentage\x12\x1f\n" +
	"\vtotal_cores\x18\x03 \x01(\rR\n" +
	"totalCores\x12!\n" +
	"\ftotal_memory\x18\x04 \x01(\rR\vtotalMemory\x12)\n" +
	"\x10available_memory\x18\x05 \x01(\rR\x0favailableMemory\x12-\n" +
	"\x06status\x18\x06 \x01(\x0e2\x15.kinetix.WorkerStatusR\x06status\x12)\n" +
	"\x10integrity_report\x18\a \x01(\tR\x0fintegrityReport\"p\n" +
	"\vBrainSignal\x12-\n" +
	"\x04task\x18\x01 \x01(\v2\x17.kinetix.TaskAssignmentH\x00R\x04task\x12)\n" +
	"\x03ack\x18\x02 \x01(\v2\x15.kinetix.HeartbeatAckH\x00R\x03ackB\a\n" +
	"\x05event\"\xd5\x01\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vwasm_binary\x18\x02 \x01(\fR\n" +
	"wasmBinary\x12\x1d\n" +
	"\n" +
	"fuel_limit\x18\x03 \x01(\rR\tfuelLimit\x122\n" +
	"\x03env\x18\x04 \x03(\v2 .kinetix.TaskAssignment.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\fHeartbeatAck\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime*J\n" +
	"\fWorkerStatus\x12\b\n" +
	"\x04IDLE\x10\x00\x12\b\n" +
	"\x04BUSY\x10\x01\x12\x0f\n" +
	"\vTERMINATING\x10\x02\x12\x15\n" +
	"\x11CRITICAL_RESOURCE\x10\x032N\n" +
	"\fOrchestrator\x12>\n" +
	"\tSubscribe\x12\x15.kinetix.WorkerSignal\x1a\x14.kinetix.BrainSignal\"\x00(\x010\x01B/Z-github.com/Rajat-Bansal3/kinetix/shared/protob\x06proto3"

var (
	file_kinetix_proto_rawDescOnce sync.Once
	file_kinetix_proto_rawDescData []byte
)

func file_kinetix_proto_rawDescGZIP() []byte {
	file_kinetix_proto_rawDescOnce.Do(func() {
		file_kinetix_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kinetix_proto_rawDesc), len(file_kinetix_proto_rawDesc)))
	})
	return file_kinetix_proto_rawDescData
}

var file_kinetix_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kinetix_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kinetix_proto_goTypes = []any{
	(WorkerStatus)(0),      // 0: kinetix.WorkerStatus
	(*WorkerSignal)(nil),   // 1: kinetix.WorkerSignal
	(*BrainSignal)(nil),    // 2: kinetix.BrainSignal
	(*TaskAssignment)(nil), // 3: kinetix.TaskAssignment
	(*HeartbeatAck)(nil),   // 4: kinetix.HeartbeatAck
	nil,                    // 5: kinetix.TaskAssignment.EnvEntry
}
var file_kinetix_proto_depIdxs = []int32{
	0, // 0: kinetix.WorkerSignal.status:type_name -> kinetix.WorkerStatus
	3, // 1: kinetix.BrainSignal.task:type_name -> kinetix.TaskAssignment
	4, // 2: kinetix.BrainSignal.ack:type_name -> kinetix.HeartbeatAck
	5, // 3: kinetix.TaskAssignment.env:type_name -> kinetix.TaskAssignment.EnvEntry
	1, // 4: kinetix.Orchestrator.Subscribe:input_type -> kinetix.WorkerSignal
	2, // 5: kinetix.Orchestrator.Subscribe:output_type -> kinetix.BrainSignal
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_kinetix_proto_init() }
func file_kinetix_proto_init() {
	if File_kinetix_proto != nil {
		return
	}
	file_kinetix_proto_msgTypes[1].OneofWrappers = []any{
		(*BrainSignal_Task)(nil),
		(*BrainSignal_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kinetix_proto_rawDesc), len(file_kinetix_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kinetix_proto_goTypes,
		DependencyIndexes: file_kinetix_proto_depIdxs,
		EnumInfos:         file_kinetix_proto_enumTypes,
		MessageInfos:      file_kinetix_proto_msgTypes,
	}.Build()
	File_kinetix_proto = out.File
	file_kinetix_proto_goTypes = nil
	file_kinetix_proto_depIdxs = nil
}
